PRAGMA FOREIGN_KEYS = ON;
PRAGMA JOURNAL_MODE = WAL;
PRAGMA SYNCHRONOUS = NORMAL;

CREATE TABLE IF NOT EXISTS `USERS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `NAME` VARCHAR(64)  NOT NULL,
    `EMAIL` VARCHAR(64)  NOT NULL,
    `PASSWORD` VARCHAR(64)  NOT NULL,
    `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS `TICKETS` (
    `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `MUSEUM_ID` INTEGER NOT NULL,
    `PRICE` DECIMAL(10, 2) DEFAULT 50.00,
    `DATE` DATETIME,

    FOREIGN KEY(`USER_ID`) REFERENCES `USERS`(`ID`) ON DELETE CASCADE,
    FOREIGN KEY(`MUSEUM_ID`) REFERENCES `MUSEUMS`(`ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `MUSEUMS` (
    `ID`  INTEGER PRIMARY KEY AUTOINCREMENT,
    `NAME`   TEXT NOT NULL,
    `ADDRESS` TEXT NOT NULL,
    `SEATS` INTEGER DEFAULT -1
);

CREATE TABLE IF NOT EXISTS `RAZORPAY_ORDERS` (
    `USER_ID` INTEGER NOT NULL,
    `TICKET_ID` INTEGER NOT NULL,
    `ORDER_ID` TEXT,
    `ORDER_STATUS` TEXT DEFAULT "UNPAID",

    FOREIGN KEY(`USER_ID`) REFERENCES `USERS`(`ID`) ON DELETE CASCADE,
    FOREIGN KEY(`TICKET_ID`) REFERENCES `TICKETS`(`ID`) ON DELETE CASCADE
);